spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # duracao 5 minutos
      
UserController:
  auth: Autentica o usuario e retorna seu token JWT.
  find: Retorna todos os repositorios do Git para o usuario informado.